### ISSUE TITLE
Clarret +2Pre error when entering commands: no such file or directory 

### ISSUE THREAD

**Issue by Jordipalsy** [geoffreybennett/scarlett-gen2#13] opened 2024-05-14 11:15 UTC
Hi,

I recently installed Linux Mint. These are my specs:

OS: Lunix Mint 21.3
Cinnamon Version: 6..0.4
Linux Kernel: 6.5.0-28-generic
Processor: AMD Ryzen 9 5900X 12-Core Processor
Ram: 32 GB
GPU: AMD Radeon 6700XT 
Interface: Clarret +2Pre
(The device works on Windows I have a dualboot for some Win apps I need).

The audio works fine. I can hear audio from both speakers connected to the interface. The headphone input works too. The thing that doesn't work are the inputs on the device. They do show a green ring when talking into one of my connected mics. I assume this means they do pick up signal. The inputs just don't show up anywhere in the sound settings. 

In an attempt to fix this, I wanted to install the mod provided here. I download the package corresponding to my current kernel I believe: snd-usb-audio-kmod-6.5-v1.3.tar.gz

I tried to follow the readme.md, but there I run into an issue.

I can execute apt-get update and sudo apt-get install linux-headers-$(uname -r) both give the output that everything is updated.

If I understand correctly, after this I need to run the next commands from within the directory from the archive I extracted.     

However, when I run: bash KSRCDIR=/lib/modules/$(uname -r)/build 
 
I get the error: no such file or directory.

What am I doing wrong? Can someone explain to me what to do step by step? (If it indeed has a change of fixing the no inputs issue). I'm a Linux beginner, just a heads up.

**Comment by geoffreybennett** [comment] 2024-05-14 14:25
Hi @Jordipalsy,

Strange as it may seem, this driver has nothing to do with getting audio working. Please see https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md for why.

> The inputs just don't show up anywhere in the sound settings.

I just installed Mint 21.3 to see what the deal is, and yeah, it does not support multi-channel audio interfaces out of the box; the sound settings app just ignores them.

Usually this problem is caused by an output-only audio configuration being selected by default, but I installed `pavucontrol` to check that, and the configuration was already "Analogue Surround 4.0 Output + Multichannel Input" (not great, but at least it will do audio in _and_ out).

Check this screenshot:

![Screenshot_mint_2024-05-14_22:03:28](https://github.com/geoffreybennett/scarlett-gen2/assets/1866657/888ae2b6-2f22-44f5-9e26-d055cffbf2be)

You can see the sound panel is missing my Clarett+ 2Pre, but pavucontrol shows it. I selected it (the green tick button) and then it is (somewhat) usable as an input in Audacity.

I say "somewhat" because PulseAudio (default audio server in Mint 21.3) treats multi-channel sound cards as surround-sound (i.e. Front-Left, Front-Right, Front-Center, LFE, Rear-Left, Rear-Right, etc.) output _and_ input! So to get sensible results in Audacity you'll need to do a 12-channel recording otherwise it will mix them down to your selected number of channels & a mono Mic recording will max out at about -21dB.

I'd suggest trying my ALSA UCM2 profile for the 2Pre here https://github.com/geoffreybennett/alsa-ucm-conf/ but Mint only has an older version of ALSA which doesn't support this.

What does work is to create virtual sound card devices. Here's what I did with success:

```
# List sources, then find the Clarett multichannel source name:

g@mint:~$ pactl list sources short
0       alsa_output.usb-Focusrite_Clarett__2Pre_00008355-00.analog-surround-40.monitor  module-alsa-card.c      s32le 4ch 44100Hz       RUNNING
1       alsa_input.usb-Focusrite_Clarett__2Pre_00008355-00.multichannel-input   module-alsa-card.c      s32le 12ch 44100Hz      RUNNING
2       alsa_output.pci-0000_00_1b.0.analog-stereo.monitor      module-alsa-card.c      s16le 2ch 44100Hz       RUNNING
3       alsa_input.pci-0000_00_1b.0.analog-stereo       module-alsa-card.c      s16le 2ch 44100Hz       RUNNING
4       output-1-2.monitor      module-remap-sink.c     s32le 2ch 44100Hz       RUNNING

g@mint:~$ pactl list sources short | grep 'Clarett.*multichannel-input'
1       alsa_input.usb-Focusrite_Clarett__2Pre_00008355-00.multichannel-input   module-alsa-card.c      s32le 12ch 44100Hz      RUNNING

g@mint:~$ pactl list sources short | grep 'Clarett.*multichannel-input' | cut -f2
alsa_input.usb-Focusrite_Clarett__2Pre_00008355-00.multichannel-input

# Put it in a variable:

g@mint:~$ SRC=$(pactl list sources short | grep 'Clarett.*multichannel-input' | cut -f2)
g@mint:~$ echo $SRC
alsa_input.usb-Focusrite_Clarett__2Pre_00008355-00.multichannel-input

# Create a new virtual mono source from input 1 (FL)
g@mint:~$ pactl load-module module-remap-source source_name=input-1 source_properties=device.description=input-1 master=$SRC channels=1 remix=no master_channel_map=front-left channel_map=mono

# Create a new virtual stereo source from input 1 & 2 (FL+FR)
g@mint:~$ pactl load-module module-remap-source source_name=input-1-2 source_properties=device.description=input-1-2 master=$SRC channels=2 remix=no master_channel_map=front-left,front-right channel_map=left,right
```

After that, the new virtual input devices are visible:

![image](https://github.com/geoffreybennett/scarlett-gen2/assets/1866657/60c4cb63-b232-46ff-9fdd-7694a4842131)

> If I understand correctly, after this I need to run the next commands from within the directory from the archive I extracted.

Correct.

> However, when I run: bash KSRCDIR=/lib/modules/$(uname -r)/build

You should not type the things on the ` ``` ` lines; those are delimiters showing the start/end of the commands to run. You should run:

```bash
KSRCDIR=/lib/modules/$(uname -r)/build
make -j4 -C $KSRCDIR M=$(pwd) clean
make -j4 -C $KSRCDIR M=$(pwd)
sudo make -j4 -C $KSRCDIR M=$(pwd) INSTALL_MOD_DIR=updates/snd-usb-audio modules_install
sudo depmod
```

> What am I doing wrong? Can someone explain to me what to do step by step? (If it indeed has a change of fixing the no inputs issue). I'm a Linux beginner, just a heads up.

Based on what I've seen, Mint is not a good distro for audio for Linux beginners, but hopefully the above info helps you get going! Please let me know if you need any more assistance.

Regards,
Geoffrey.

**Comment by Jordipalsy** [comment] 2024-05-14 16:26
Hi Geoffrey,

Thanks for your reply. Nice to see you've got it working! I must be honest, the virtual sound devices thing seems a bit too complicated for me to get working. Do you happen to have a distro where the interface works out of the box? (Or with less complicated steps?)

**Comment by Jordipalsy** [comment] 2024-05-14 19:02
Just tried Ubuntu live CD not working..

**Comment by geoffreybennett** [comment] 2024-05-15 04:49
Hi @Jordipalsy,

Depending on your requirements, Mint might be just fine. Have you tried installing pavucontrol and selecting your Clarett? That was all I needed to do to get the basics going.

Every distro is going to require some sort of configuration. I'm not sure what you mean by complicated? What happens when you copy/paste the commands I gave you into a terminal?

Personally I use Fedora, but I think Ubuntu and Ubuntu Studio are more popular. Something that comes with PipeWire rather than PulseAudio would be a good start! People have lots of opinions: https://www.reddit.com/r/linuxaudio/comments/yzby2b/which_linux_distribution_for_music_production/ :laughing:

Regards,
Geoffrey.

**Comment by Jordipalsy** [comment] 2024-05-17 09:34
Hi Geoffrey,

Yes I installed pavucontrol and selected the Clarret without succes. However, I did install Qjack and in stereo setup in Audacity, I Hear both mics. Each on one side. When selecting a mono channel, only one input works in Audacity. I would like them both to work in mono if possible. (I want to use both mics in something like Audacity, but also in video calling software for instance.)  

I tried switching to Pipewire, this is my current setting:

pactl info
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 85
Tile Size: 65472
User Name: jordi
Host Name: jordi-B550M-DS3H
Server Name: PulseAudio (on PipeWire 0.3.48)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.usb-Focusrite_Clarett__2Pre_00001459-00.analog-surround-40
Default Source: alsa_output.usb-Focusrite_Clarett__2Pre_00001459-00.analog-surround-40.monitor
Cookie: 88e1:3098

Audio playback works fine, but In qpwgraph, there are no capture inputs available:
![QPWgraph ](https://github.com/geoffreybennett/scarlett-gen2/assets/169784928/59929815-9aa6-4702-a170-712c8bd932eb)

My apologies, but I don't understand what I should be doing with this:
# List sources, then find the Clarett multichannel source name:

g@mint:~$ pactl list sources short
0       alsa_output.usb-Focusrite_Clarett__2Pre_00008355-00.analog-surround-40.monitor  module-alsa-card.c      s32le 4ch 44100Hz       RUNNING
1       alsa_input.usb-Focusrite_Clarett__2Pre_00008355-00.multichannel-input   module-alsa-card.c      s32le 12ch 44100Hz      RUNNING
2       alsa_output.pci-0000_00_1b.0.analog-stereo.monitor      module-alsa-card.c      s16le 2ch 44100Hz       RUNNING
3       alsa_input.pci-0000_00_1b.0.analog-stereo       module-alsa-card.c      s16le 2ch 44100Hz       RUNNING
4       output-1-2.monitor      module-remap-sink.c     s32le 2ch 44100Hz       RUNNING

g@mint:~$ pactl list sources short | grep 'Clarett.*multichannel-input'
1       alsa_input.usb-Focusrite_Clarett__2Pre_00008355-00.multichannel-input   module-alsa-card.c      s32le 12ch 44100Hz      RUNNING

g@mint:~$ pactl list sources short | grep 'Clarett.*multichannel-input' | cut -f2
alsa_input.usb-Focusrite_Clarett__2Pre_00008355-00.multichannel-input

# Put it in a variable:

g@mint:~$ SRC=$(pactl list sources short | grep 'Clarett.*multichannel-input' | cut -f2)
g@mint:~$ echo $SRC
alsa_input.usb-Focusrite_Clarett__2Pre_00008355-00.multichannel-input

# Create a new virtual mono source from input 1 (FL)
g@mint:~$ pactl load-module module-remap-source source_name=input-1 source_properties=device.description=input-1 master=$SOURCE channels=1 remix=no master_channel_map=front-left channel_map=mono

# Create a new virtual stereo source from input 1 & 2 (FL+FR)
g@mint:~$ pactl load-module module-remap-source source_name=input-1-2 source_properties=device.description=input-1-2 master=$SOURCE channels=2 remix=no master_channel_map=front-left,front-right channel_map=left,right

As in, what to paste and where one command starts and ends. Is there a way to get this to work in a GUI way? I suck at commandline. Hahaha!

**Comment by geoffreybennett** [comment] 2024-05-17 10:22
Hi @Jordipalsy,

PipeWire is good; that should make this easier. In `pavucontrol`, go to the Configuration tab and select the "Pro Audio" profile for your Clarett (your qpwgraph screenshot indicates that a different profile is selected). That should make the inputs show up in `qpwgraph`. You might find this is sufficient for your recording needs! Please do try, and any issues please share screenshots of your `pavucontrol` configuration, `qpwgraph`, and `audacity`.

In my CLI transcript:
- `g@mint:~$` is the terminal prompt. Don't type that; you'll have some sort of similar prompt show up when you open a terminal window.
- The rest of the line is the command I typed. E.g. `pactl list sources short` ← you should type that and press Enter
- Subsequent lines _not_ beginning with `g@mint:~$` are the output from the command.
- Line beginning with `#` are comments, explaining what the commands are doing.

You might want to be copy-pasting rather than retyping the commands because near enough isn't good enough. E.g. the difference between `` ` `` and ` ' ` is critical. I did spot a typo in my commands, which I've fixed now (had `SOURCE` instead of `SRC`).

Again, any issues, please share screenshots of your command window so I can see what's happening.

A GUI way? That would be nice. I've not seen a GUI for configuring virtual soundcards, but as I said above, with PipeWire and the Pro Audio profile, you might not need to do this. The Pro Audio profile without any further configuration works well in many cases.

Also, could you share the instructions you used to install PipeWire? I will do the same on my Mint install so I can follow along with what you're doing and provide some more advice.

Regards,
Geoffrey.

**Comment by geoffreybennett** [comment] 2024-05-17 10:33
One more thing, when you're copy-pasting commands and their output into GitHub comments like above, put three back-ticks: ` ``` ` before and after, otherwise this:

```
# Put it in a variable:

g@mint:~$ SRC=$(pactl list sources short | grep 'Clarett.*multichannel-input' | cut -f2)
g@mint:~$ echo $SRC
alsa_input.usb-Focusrite_Clarett__2Pre_00008355-00.multichannel-input
```
turns into this:
![image](https://github.com/geoffreybennett/scarlett-gen2/assets/1866657/4d8dae1d-8274-440c-b5ce-e316960e418d)
because GitHub comments treat `~strikethrough~` as ~strikethrough~ and `#` as headings. You can use the "Preview" tab before you click "Comment" to see what it's going to look like.

See here: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks for more info.

**Comment by Jordipalsy** [comment] 2024-05-17 11:24
Hi Geoffrey,

Audacity works in pro mode! (Here's the setup now)
![qwph graph pro mode](https://github.com/geoffreybennett/scarlett-gen2/assets/169784928/e8b4d327-0cc4-4b67-974a-ce3bd844cb40)

 Both mics are being picked up as mono source. Which is what I want. (The mics need significantly more gain as opposed to Windows. However, that can be just a setting somewhere).  I assume it will also work in Ardour if I ever want to use it? 

One last thing I would like is, make the mics work in a browser version of for example: Teams, Google Meet, DIscord, etc... However, when I click start test, there's no Pipewire to select:
![Can't select Pipewire](https://github.com/geoffreybennett/scarlett-gen2/assets/169784928/e367d5fb-7aa3-4d58-b73f-53fcc7fc3c13)

Do you know a way to make that work as well? (My assumption was that the point of Pipewire aims to make devices and it's inputs work with all the applications you use). Since I'm A beginner, there's a huge change I'm wrong though. Thanks for your help man! Appreciate your patience.

Commands used to install Pipewire:
```sudo apt install pipewire-audio-client-libraries libspa-0.2-bluetooth libspa-0.2-jack wireplumber```

```systemctl --user --now enable wireplumber.service```

```reboot```

Regards.
Jordi

**Comment by geoffreybennett** [comment] 2024-05-18 16:28
Hi @Jordipalsy,

I installed pipewire as per your instructions, but it looks like that installed version 0.3.48 which is over two years old:
![image](https://github.com/geoffreybennett/scarlett-gen2/assets/1866657/48a6b361-cc7e-452f-b663-6dbf67fedd00)
https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.48 — 
"PipeWire 0.3.48 (2022-03-03)", and it seems to be missing `pipewire-jack`.

What version do you have running?

> Both mics are being picked up as mono source. Which is what I want.

That's probably dependent on the application that you're running. I suspect that's a bit more complicated than that, especially since you say the gain is low. Possibly the audio is being treated as stereo, then mixed down to mono, with the volume in one channel therefore being 50% of what it should be.

> (The mics need significantly more gain as opposed to Windows. However, that can be just a setting somewhere).

Check in `pavucontrol` that the input level is set to 100%. Then check `qpwgraph` to see which inputs are actually connected to your application. We'll get this sorted, but you need a good install of pipewire first.

> I assume it will also work in Ardour if I ever want to use it?

If `pipewire-jack` is installed/working then Ardour will work great as it's designed to work with multi-channel audio interfaces unlike Audacity, etc.

> One last thing I would like is, make the mics work in a browser version of for example: Teams, Google Meet, DIscord, etc... However, when I click start test, there's no Pipewire to select:

You don't need to select PipeWire because that's what it's already using. The in-browser selection of "Clarett+ 2Pre Pro" is correct, and corresponds to this box in qpwgraph:

![image](https://github.com/geoffreybennett/scarlett-gen2/assets/1866657/9538bc29-b939-4737-9ee9-4eca12337c7b)

I tried this myself though, and it doesn't work. I suspect the Mint pipewire packages are broken.

I found this: https://www.reddit.com/r/linux4noobs/comments/16fw6b0/how_do_i_install_pipewirepulse_and_pipewirejack/:

> >  When I installed Linux Mint, it came with both "PulseAudio" and "Pipewire". I would like to primarily use Pipewire so I can install Wireplumber and reroute my audio. 
>
>  Note that Mint ships a ancient version of Pipewire, which could cause issues. Use [a PPA](https://pipewire-debian.github.io/pipewire-debian/) to get a newer version, or consider a more up-to-date distro.

Let me know what you choose here & I'll follow along again. Sorry I know little about Mint; I'm not sure if it's better to try installing a newer PipeWire or get a more up-to-date distro.

**Comment by Jordipalsy** [comment] 2024-05-19 12:04
Hi @geoffreybennett,

Here's the pactl output:

$ pactl info
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 348
Tile Size: 65472
User Name: jordi
Host Name: jordi-B550M-DS3H
Server Name: PulseAudio (on PipeWire 0.3.48)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.usb-Focusrite_Clarett__2Pre_00001459-00.pro-output-0
Default Source: alsa_input.usb-Focusrite_Clarett__2Pre_00001459-00.pro-input-0
Cookie: ceff:c88f

Outdated like you said. I'm not sure how to add or use PPA's when there are no tutorials since I'm not good at terminal stuff. I've read that Fedora, the distro you use, ships with Pipewire as default audio server out of the box? Is pipewire-jack also installed? Could you check whether on Fedora, testing the mic works when selecting the Clarret+2 pre?
https://www.onlinemictest.com/

 I suspect me switching to Fedora is easier then to figure out how to add PPA'S and then update pipewire? Can you advice on if Fedora will be a good fit for my limited knowledge of Linux?

The other option is to wait for Mint 22 as it's supposed to ship with Pipewire 1.0      

PS: Sorry I've added ``` before and after the terminal output and pressed enter to start a new paragraph, but it won't change back to regular text so, I'll leave it like this.

**Comment by Jordipalsy** [comment] 2024-05-19 12:10
I guess Pipewire-jack isn't in the repository at all see:

```~$ sudo apt install pipewire-pulse pipewire-jack
[sudo] password for jordi:          
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package pipewire-jack

**Comment by geoffreybennett** [comment] 2024-05-19 13:37
Hi @Jordipalsy,

Fedora does use PipeWire out of the box; that's one of its advantages, often including the latest and greatest technologies, but sometimes being on the bleeding edge is problematic too (don't get me started on Wayland). Yes to pipewire-jack as well.

I can say that every Focusrite Scarlett, Clarett, and Vocaster USB interface works on Fedora, but there's no reason they won't work similarly well on any other up-to-date distribution.

Sorry, I don't really know what distro is good for a new Linux user. I've been using Linux as my desktop OS since the early 90s, and Fedora for most of that time, so my use of Linux is about as far removed from "new user" as you can get.

I tried https://www.onlinemictest.com/ — it works in Firefox and Chrome. I regularly use Skype, Discord, WebEx, and Teams on Linux. Sometimes they can be fiddly; it's not like Linux is the top platform for any of those apps.

Regards,
Geoffrey.

**Comment by anolting** [comment] 2024-05-19 17:25
@Jordipalsy  so, i'm throwing in my 2 cents now. 
If you want to stick with Ubuntu try https://ubuntustudio.org/. 

If you are willing to learn how to build and setup you own DAW "distro" you give ARCH based distros a try: endeavouros - https://endeavouros.com/ or manjaro - https://manjaro.org/. Both offer Low Latency kernels and are preconfigured with Pipewire in its latest version.

Then there is a hobbyist's project call AV Linux - http://www.bandshed.net/ - Ubuntu based as well. This is DAW distro with many audio software preinstalled and offers also support for proprietary software like Cockos Reaper.
and last known (at least for me) is https://kx.studio/News/ - KX Studio, which is also a DAW distro.

Some of them offer a Live media allowing you to try it before install it.

UPDATE: In case of pipewire and Ubuntu, there are user out there using Debian repos along with their Ubuntu install like this one: https://launchpad.net/~pipewire-debian/+archive/ubuntu/pipewire-upstream. But this repo is also not up-to-date. If you are not very experienced managing and setting up software which is close to core functionality I wouldn't recommend you to play with such repos.

**Comment by Jordipalsy** [comment] 2024-05-20 11:31
Hi @geoffreybennett and @anolting,

First of all, thanks for both of your replies. I went ahead and installed Manjaro. I like the idea of the distro. All the controversy aside, I want to give it a try.

This is now my pactl output:

Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 104
Tile Size: 65472
User Name: jordi
Host Name: jordi-b550mds3h
Server Name: PulseAudio (on PipeWire 1.0.5)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.usb-Focusrite_Clarett__2Pre_00001459-00.pro-output-0
Default Source: alsa_input.usb-Focusrite_Clarett__2Pre_00001459-00.pro-input-0
Cookie: 097a:4fc2

I also went ahead and enabled 'pro audio' for the Clarret after installing Pavucontrol. Funny thing is, the mics work in Audacity and Chormiun but not in Firefox.

The other small issue in audacity is the low gain.

 If one or both of you want to help getting  these small issues can be fixed, that would be great. If not, all good. Appreciate the help up to this point!
 
 Regards,
 Jordi

**Comment by anolting** [comment] 2024-05-20 12:23
As of my knowledge Firefox on arch has still alsa compiled in. I suggest installing pipewire-alsa package along with alsamixer for setting up proper volume and gain level may solve your issues.
Btw I'm only using Scarlett 3rd gen on endeavoros. So I cannot test this myself but I have (ok the Installation is rather old) pipewire with alsa components along with alsamixer installed and have no issues at all in any software selecting different mics.

**Comment by geoffreybennett** [comment] 2024-05-20 12:38
Hi @Jordipalsy,

That's good news! :) To fix the gain issue, I'd first check in pavucontrol on the Recording and Input Devices tabs. Make sure the sliders are at 100%.

Regards,
Geoffrey.

**Comment by Jordipalsy** [comment] 2024-05-21 12:43
@anolting Here you can see Pipewire-Alsa is installed:
![Pipewire alsa](https://github.com/geoffreybennett/scarlett-gen2/assets/169784928/94665aff-a673-410d-8b32-320c1e02c2ad)

@geoffreybennett The gain is set to 100% see:
![Volume settings](https://github.com/geoffreybennett/scarlett-gen2/assets/169784928/2625eb8b-4bcf-4b1d-98cb-39f8e6fd1151)

Here you see a recording with the gain set to 3pm:
![Low gain](https://github.com/geoffreybennett/scarlett-gen2/assets/169784928/0e8c2ebe-5af1-48ce-8b83-89d0950de921)


For reference, on Win I can set it to 12 pm and that's a little too loud most of the time. I can of course use a compressor after recording but it's not ideal.

Great day to you both!
Jordi

**Comment by geoffreybennett** [comment] 2024-05-21 13:20
Hi @Jordipalsy,

Few more things to check:
- Recording tab of pavucontrol — while recording, is the app at 100%? (if the app uses JACK, it might not show up in here at all and that's okay)
- In alsa-scarlett-gui, what do the routing and levels windows show?
- Do some tests with audacity with the input gain maxed out so you are clipping; what does that show on the inputs?
- Or with ardour, what does that show on the inputs?

If you turn the input gain on the interface fully clockwise and make the light go red, but it's not showing 100%/0dB in audacity/ardour then that's a sign.

I've never used Reaper, so not sure how to interpret your screenshot.

Here's what I see with ardour and pavucontrol when I'm clipping on mic input 1:
![Screenshot from 2024-05-21 22-21-38](https://github.com/geoffreybennett/scarlett-gen2/assets/1866657/b4c3e6fb-6446-45e0-9764-4dca38f84a8b)
As expected, ardour shows 0dB. pavucontrol shows 50% because it is treating mic inputs 1 & 2 as stereo.

This is what I see in alsa-scarlett-gui:
![image](https://github.com/geoffreybennett/scarlett-gen2/assets/1866657/193e917a-d439-4832-98bf-33ab6554ac2f)

I did some tests in audacity:
![image](https://github.com/geoffreybennett/scarlett-gen2/assets/1866657/a3253e69-5cf7-48b4-9da1-f68eb115a0ae)
Track 1 is JACK/Clarett+ 2Pre Pro, Mono recording, goes to 100% because it's recording input 1 only
Track 2 is ALSA/Pipewire, Mono recording, only goes to 50% because the inputs 1 & 2 get mixed down to mono
Track 3 is Stereo recording, doesn't matter if JACK or ALSA/Pipewire because the inputs 1 & 2 are recorded separately.

This is my routing configuration:

![Screenshot from 2024-05-21 22-37-41](https://github.com/geoffreybennett/scarlett-gen2/assets/1866657/0896c163-a077-4e40-8034-7615bce13401)

If I had software that insisted on using the PCM 1/2 inputs mixed down to mono (like you see in Audacity Track 2), then I would route Hardware Input Analogue 1 to PCM Input 2.

So, try the above experiments & let us know where things diverge!

Regards,
Geoffrey.

**Comment by Jordipalsy** [comment] 2024-05-21 14:28
Hi @geoffreybennett 

This is what I see in Scarlett gui:
![Alsa gui](https://github.com/geoffreybennett/scarlett-gen2/assets/169784928/27dac60d-2717-4e15-8c51-7189f414c086)

A recording fully clockwise indeed clips the signal as seen here:
![Full clockwise](https://github.com/geoffreybennett/scarlett-gen2/assets/169784928/f0342431-90fc-4c99-8a1e-7957143abca7)

I assume that's a good sign? (the clipping)

I used ALSA by the way.

I'm I correct in thinking that to get good results, it's not 'bad' to turn the gain up more then in Windows? As long as I have headroom to mix the audio later, that's all that matters to me.

Is there anything you would change looking at my gui settings?

Any new insights to getting the mics working within Firefox? (If it has to be chromuim fine).

Regards,
Jordi

**Comment by geoffreybennett** [comment] 2024-05-22 13:03
Hi @Jordipalsy,

Again, I'm not familiar with Reaper, but that screenshot to me says you're not clipping — the waveform doesn't quite reach the top/bottom edge, and I'm guessing that the "-0.2" shown next to the waveform is the peak level, also "not quite clipping".

Given that you're able to almost reach 0dBFS I'm not seeing any problem here. My worry when you said that the volume was lower in Linux than Windows was that multiple channels were being mixed together which would result in 50% or less volume than expected, but that doesn't seem to be the case. I think it's more likely now that you've just got different settings in Reaper between Windows and Linux and having to turn the gain up to compensate.

Regards,
Geoffrey.

**Closed as completed** 2024-06-05 10:59 UTC
